window.addEventListener('error',e=>{if(e.message)document.body.dataset.previewError=e.message});
window.addEventListener('unhandledrejection',e=>document.body.dataset.previewError=String(e.reason?.message||e.reason));
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const image=(src,alt,cls='',eager=false)=>`<img class="${cls}" src="${src}" alt="${alt}" ${eager?'fetchpriority="high"':'loading="lazy"'}>`;
const tag=(n,t)=>`<div class="eyebrow"><span>${n}</span>${t}</div>`;
const title=(a)=>a[0]+'<br><em>'+a[1]+'</em>';
let sequence=0;
const heading=(label,t)=>`${tag(String(++sequence).padStart(2,'0'),label)}<h2 class="reveal">${title(t)}</h2>`;
const P=window.PROJECTS.find(p=>p.id===document.body.dataset.project);
window.caseData=P;
for(const [k,v] of Object.entries({ink:P.ink,paper:P.paper,accent:P.accent,soft:P.soft,'project-font':P.font}))document.documentElement.style.setProperty('--'+k,v);
document.body.classList.toggle('light-opening',!P.heroDark);
const frame=(page,label,kind='desktop')=>`<div class="screen-content screen-${kind}"><iframe inert aria-hidden="true" data-page="${page}" data-kind="${kind}" data-width="${kind==='mobile'?390:1440}" title="${label} — original page exhibit" tabindex="-1" sandbox="allow-scripts allow-same-origin" loading="lazy"></iframe></div>`;
const phone=(page,label,cls)=>`<div class="phone ${cls}"><div class="phone-screen">${frame(page,label,'mobile')}</div><i class="island" aria-hidden="true"></i><i class="home-indicator" aria-hidden="true"></i><span class="phone-label">${label}</span></div>`;
const laptop=(page,label,cls)=>`<div class="laptop ${cls}"><div class="laptop-lid"><i class="lens" aria-hidden="true"></i><div class="laptop-screen">${frame(page,label)}</div><div class="laptop-chin">MacBook Pro</div></div><div class="laptop-base"><i></i></div><span class="laptop-caption">${label}</span></div>`;
const pages=P.pages||[],hasPages=pages.length>0,first=pages[0],second=pages[1],third=pages[2],flow=pages.slice(0,3);
const contrast=c=>{if(c.startsWith('oklch'))return c.includes('96%')?P.ink:P.paper;const h=c.replace('#','');const rgb=[0,2,4].map(i=>parseInt(h.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4));return rgb[0]*.2126+rgb[1]*.7152+rgb[2]*.0722>.36?P.ink:P.paper};
document.querySelector('#case').innerHTML=`
<section class="hero dark" id="opening"><div class="hero-art">${image(P.hero,P.name+' / original project artwork','',true)}</div><div class="hero-copy"><p class="project-type">${P.type}</p>${image(P.logo,P.name,'hero-logo',true)}<h1 id="hero-title"><span class="line"><span>${P.title[0]}</span></span><span class="line"><em>${P.title[1]}</em></span></h1><p class="hero-deck">${P.deck}</p><a class="text-link" href="#story">Explore the collaboration ${arrow}</a></div><div class="hero-bottom"><span>A PULSE CASE STUDY</span><span>${P.name.toUpperCase()}</span><a href="#story" aria-label="Scroll to the collaboration">↓</a></div></section>
<section class="story paper chapter" id="story"><div class="project-details"><div><span class="meta-label">Project</span><p>${P.name}</p></div><div><span class="meta-label">Project type</span><p>${P.type}</p></div><div><span class="meta-label">Project scope</span><div class="scope-list">${P.scopes.map((s,i)=>`<button data-scope="${i}">${s}<span>↗</span></button>`).join('')}</div></div></div><div class="story-main">${heading('THE COLLABORATION',P.story)}<div class="story-columns"><article><h3>Project goal</h3><p>${P.goal}</p></article><article><h3>Our solution</h3><p>${P.solution}</p></article></div></div></section>
<section class="strategy dark chapter" id="strategy"><div class="strategy-art">${image(P.strategy,P.name+' / original visual direction')}</div><div class="strategy-copy">${heading('STYLE STRATEGY',P.style)}<div class="principles">${P.principles.map(([n,d],i)=>`<article><span>0${i+1}</span><div><h3>${n}</h3><p>${d}</p></div></article>`).join('')}</div></div></section>
<section class="palette paper chapter" id="identity">${heading('COLOR PALETTE',['A recognisable','spectrum.'])}<div class="swatches">${P.palette.map(([n,c,r],i)=>`<button class="swatch" style="--color:${c};color:${contrast(c)}" data-color="${c}" aria-label="Inspect ${n} ${c}"><span class="swatch-index">0${i+1}</span><div><h3>${n}</h3><p>${r}</p><span>${c}</span></div><i aria-hidden="true">+</i></button>`).join('')}</div><p class="palette-status" id="palette-status" aria-live="polite">Select a color.</p></section>
<section class="typography paper chapter" id="typography"><div class="type-top">${tag(String(++sequence).padStart(2,'0'),'TYPOGRAPHY')}<span>${P.fontName}</span></div><div class="type-main"><div class="type-aa">Aa</div><div><h2>Words with<br>character.</h2></div></div><div class="type-controls"><label for="weight">Weight<select id="weight"><option value="400">Regular / 400</option><option value="600">Semibold / 600</option></select></label><label for="specimen-input">Try your own words<input id="specimen-input" maxlength="80" value="${P.sample}"></label></div><p id="type-specimen">${P.sample}</p><div class="alphabet">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz &nbsp; 0123456789</div></section>
<section class="logo chapter" id="logo" style="background:${P.logos[0][1]};color:${contrast(P.logos[0][1])}"><div class="logo-top">${tag(String(++sequence).padStart(2,'0'),'THE BRAND MARK')}</div>${image(P.logos[0][0],P.name+' original brand mark','main-logo')}<div class="logo-bottom"><span>${P.name.toUpperCase()}</span></div></section>
<section class="variations chapter" id="variations" aria-label="Original identity assets">${P.logos.map(([src,bg,label],i)=>`<div class="mark-cell" style="background:${bg};color:${contrast(bg)}">${image(src,label)}<div><span>0${i+1}</span><span>${label}</span></div></div>`).join('')}</section>
<section class="applications dark chapter" id="applications"><div class="application-heading">${heading('THE IDENTITY IN USE',['From direction','to detail.'])}</div><div class="application-images">${P.applications.map(([src,label])=>`<figure>${image(src,label)}<figcaption>${label}</figcaption></figure>`).join('')}</div></section>
${hasPages?`
<section class="ux paper chapter" id="ux"><div class="ux-copy">${heading('UX / UI',['A clear path','through the experience.'])}<div class="flow-steps">${flow.map((p,i)=>`<button data-flow="${p.id}" aria-pressed="${i===0}"><span>0${i+1}</span><div>${p.label}</div>${arrow}</button>`).join('')}</div></div><div class="ux-device">${phone(first.id,first.label,'ux-phone')}<span class="device-note" id="flow-note">01 / ${first.label}</span></div></section>
<section class="desktop-chapter chapter" id="digital"><div class="desktop-stage"><div class="device-heading">${heading('THE LANDING EXPERIENCE',['Step into','the experience.'])}</div><div class="desk-wall" aria-hidden="true"></div><div class="desk-plane" aria-hidden="true"></div><div class="imac"><div class="imac-frame"><div class="imac-screen">${frame(first.id,first.label)}</div><div class="imac-chin"><i></i></div></div><div class="imac-neck"></div><div class="imac-foot"></div></div><div class="scene-controls"><span id="mac-state">MAC ON TABLE / SCROLL TO ENTER</span><button id="replay-mac">Replay approach ${arrow}</button></div></div></section>
<div class="screen-footnote"><span>Original project pages${P.id==='pulse-growth-engine'?' / archive':''}</span>${P.url?`<a href="${P.url}" target="_blank" rel="noopener">Explore the website ↗</a>`:''}</div>`:''}
${P.scene?`<section class="spatial dark chapter ${P.scene.kind==='web'?'spatial-mac':''}" id="spatial"><div class="spatial-heading">${heading('3D / THE ORIGINAL WORK',['A world with','dimension.'])}</div><div class="spatial-device"><div id="spline-slot" class="spline-slot">${image(P.scene.poster,'Original '+P.name+' spatial work','spline-poster')}<div class="scene-launch"><button id="load-scene" class="solid-button">Explore the original ${arrow}</button><span id="scene-status" role="status">${P.scene.kind==='model'?'Original DNA ring model':P.scene.kind==='web'?'Original WebGL experience':'Original Spline scene'}</span></div></div>${P.scene.kind==='web'?'<div class="spatial-chin"></div><div class="imac-neck"></div><div class="imac-foot"></div>':''}</div><div class="spatial-bottom"><span>ORIGINAL PROJECT SCENE</span><button id="unload-scene" hidden>Return to the still ${arrow}</button></div></section>`:''}
${hasPages?`<section class="paired paper chapter" id="paired"><div class="paired-heading">${heading('OTHER KEY PAGES',['Two perspectives.','One language.'])}</div><div class="paired-laptops" data-focus="both">${laptop(second.id,second.label,'upper')}${laptop(third.id,third.label,'lower')}</div><div class="pair-controls" aria-label="Inspect laptop screens"><button data-focus="upper" aria-pressed="false">${second.label}</button><button data-focus="both" aria-pressed="true">Both screens</button><button data-focus="lower" aria-pressed="false">${third.label}</button><button data-replay="paired">Replay ↻</button></div></section>
<section class="gallery paper chapter" id="gallery"><div class="gallery-heading">${heading('PAGE GALLERY',['Every page,','a purpose.'])}<div class="gallery-tabs">${pages.slice(1).map((p,i)=>`<button data-gallery="${p.id}" aria-pressed="${i===0}"><span>0${i+1}</span>${p.label}</button>`).join('')}</div></div><div class="browser-frame"><div class="browser-bar"><div><i></i><i></i><i></i></div><span id="gallery-address">${P.name} / ${second.label}</span><button data-replay="gallery" aria-label="Replay selected page">↻</button></div><div class="gallery-screen">${frame(second.id,second.label)}</div></div></section>
<section class="mobile chapter" id="mobile"><div class="mobile-heading">${heading('THE MOBILE EXPERIENCE',['A smaller screen.','The same intention.'])}</div><div class="phone-group ${P.mobileCount===1?'single-phone':''}">${flow.slice(0,P.mobileCount||3).map((p,i)=>phone(p.id,'0'+(i+1)+' / '+p.label,['phone-left','phone-center','phone-right'][i])).join('')}</div><div class="mobile-controls"><span>${P.mobileCount===1?'THE ORIGINAL ENTRY PAGE':'THREE MOMENTS / ONE JOURNEY'}</span><button data-replay="mobile">Replay the journey ${arrow}</button></div></section>`:''}
${P.artGallery?`<section class="artifact-gallery paper chapter" id="gallery">${heading(P.id==='vodkiss'?'THE PACKAGING RANGE':'ORIGINAL PRODUCT DESIGN',['A system,','in application.'])}<div class="artifact-grid">${P.artGallery.map(([src,label])=>`<figure>${image(src,label)}<figcaption>${label}</figcaption></figure>`).join('')}</div></section>`:''}
${P.film?`<section class="original-film dark chapter" id="motion"><div>${heading('ORIGINAL MOTION',['The identity,','in motion.'])}</div><video controls playsinline preload="metadata" src="${P.film}" poster="${P.hero}" aria-label="Original ${P.name} film"></video></section>`:''}
<section class="reflection paper chapter" id="reflection"><div>${tag(String(++sequence).padStart(2,'0'),'LOOKING AT THE WHOLE')}<h2>A coherent world.<br><em>From idea to detail.</em></h2></div><div class="reflection-copy"><details class="credits"><summary>Case notes & project credits <span>+</span></summary><p>${P.notes}</p><a href="sources.html#${P.id}">Sources & scope ↗</a></details></div></section>
<footer class="case-footer dark"><p>${P.name.toUpperCase()} / A PULSE CASE STUDY</p><a href="index.html">Back to<br><em>the collection.</em>${arrow}</a><div><span>Strategy. Identity. Experience.</span><a href="#opening">Back to top ↑</a></div></footer>`;
const names={opening:'Opening',story:'Goal & solution',strategy:'Style strategy',identity:'Color palette',typography:'Typography',logo:'Brand logo',variations:'Identity assets',applications:'Identity in use',ux:'UX / UI',digital:'Mac landing experience',spatial:'Original 3D scene',paired:'Paired MacBooks',gallery:'Gallery',mobile:'Mobile experience',motion:'Original motion',reflection:'Notes & credits'};
const chapters=[...document.querySelectorAll('main>section[id]')];
document.querySelector('#index-links').innerHTML=chapters.map((s,i)=>`<a href="#${s.id}"><span>${String(i+1).padStart(2,'0')}</span>${names[s.id]}${arrow}</a>`).join('');
document.querySelectorAll('.chapter-nav>a').forEach(a=>{if(!document.querySelector(a.hash))a.remove()});
const indexDialog=document.querySelector('#index-dialog'),scopeDialog=document.querySelector('#scope-dialog');
document.querySelector('#index-open').onclick=()=>indexDialog.showModal();document.querySelector('#index-close').onclick=()=>indexDialog.close();document.querySelector('#scope-close').onclick=()=>scopeDialog.close();
document.querySelectorAll('#index-links a').forEach(a=>a.onclick=()=>indexDialog.close());
for(const d of [indexDialog,scopeDialog])d.addEventListener('click',e=>{if(e.target===d){const b=d.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)d.close()}});
document.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{const name=P.scopes[+b.dataset.scope];document.querySelector('#scope-name').textContent=name;document.querySelector('#scope-description').textContent='Explore this contribution in the project.';let ids=/3D|Spatial/.test(name)?['story','spatial','digital']:/UX|Workflow|Product|game/.test(name)?['story','ux','digital','gallery','mobile']:/packaging|Label/.test(name)?['strategy','applications','gallery']:['story','strategy','identity','typography','logo','applications'];document.querySelector('#scope-links').innerHTML=ids.filter(id=>document.getElementById(id)).map(id=>`<a href="#${id}">${names[id]} ${arrow}</a>`).join('');document.querySelectorAll('#scope-links a').forEach(a=>a.onclick=()=>scopeDialog.close());scopeDialog.showModal()});
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-color]').forEach(x=>x.removeAttribute('aria-pressed'));b.setAttribute('aria-pressed','true');document.querySelector('#palette-status').textContent=b.querySelector('h3').textContent+' / '+b.dataset.color});
document.querySelector('#weight').onchange=e=>document.querySelector('#type-specimen').style.fontWeight=e.target.value;
document.querySelector('#specimen-input').oninput=e=>document.querySelector('#type-specimen').textContent=e.target.value||P.sample;
function sizeFrame(f){const wrap=f.parentElement,w=+f.dataset.width;if(!wrap.clientWidth)return;f.style.width=w+'px';f.style.height=(wrap.clientHeight/(wrap.clientWidth/w))+'px';f.style.transform=`scale(${wrap.clientWidth/w})`;}
window.sizeFrames=()=>document.querySelectorAll('iframe[data-page]').forEach(sizeFrame);
function source(f){return `screen.html?project=${P.id}&page=${f.dataset.page}&kind=${f.dataset.kind}`}
const frameObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const f=e.target;if(!f.src){f.src=source(f);f.onload=()=>sizeFrame(f)}sizeFrame(f)}}),{rootMargin:'400px'});
document.querySelectorAll('iframe[data-page]').forEach(f=>frameObserver.observe(f));new ResizeObserver(()=>window.sizeFrames()).observe(document.querySelector('#case'));
function changeFrame(f,page){f.dataset.page=page;delete f.dataset.ready;f.src=source(f);f.onload=()=>sizeFrame(f);window.restartPlayback?.(f.closest('section').id)}
document.querySelectorAll('[data-flow]').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('[data-flow]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));changeFrame(document.querySelector('.ux iframe'),b.dataset.flow);document.querySelector('#flow-note').textContent='0'+(i+1)+' / '+pages.find(p=>p.id===b.dataset.flow).label});
document.querySelectorAll('button[data-focus]').forEach(b=>b.onclick=()=>{document.querySelector('.paired-laptops').dataset.focus=b.dataset.focus;document.querySelectorAll('button[data-focus]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));setTimeout(window.sizeFrames,50)});
document.querySelectorAll('[data-gallery]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-gallery]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));changeFrame(document.querySelector('.gallery iframe'),b.dataset.gallery);document.querySelector('#gallery-address').textContent=P.name+' / '+pages.find(p=>p.id===b.dataset.gallery).label});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='portfolio-ready')return;document.querySelectorAll('iframe[data-page]').forEach(f=>{if(f.contentWindow===e.source){f.dataset.ready='true';sizeFrame(f)}})});
window.sizeFrames();
if(location.hash)requestAnimationFrame(()=>document.getElementById(location.hash.slice(1))?.scrollIntoView({behavior:'instant',block:'start'}));
