(()=>{
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let paused=reduced.matches,last=0,raf=0,active=null,macGeometry=null,splineFrame=null,sceneTimeout=null;
const times=new Map(),seen=new Set(),running=new Set(),visible=new Map();
const ease=t=>1-Math.pow(1-t,4),clamp=n=>Math.max(0,Math.min(1,n));
const mac=document.querySelector('#digital'),stage=mac?.querySelector('.desktop-stage'),imac=mac?.querySelector('.imac'),macScreen=mac?.querySelector('.imac-screen'),macFrame=mac?.querySelector('iframe');
const toggle=document.querySelector('#motion-toggle');
function reflectPause(){document.body.classList.toggle('paused',paused);toggle.setAttribute('aria-pressed',String(paused));toggle.innerHTML=(paused?'Play motion':'Pause motion')+' <svg viewBox="0 0 20 20" aria-hidden="true"><path d="M7 4v12M13 4v12"/></svg>';document.body.dataset.motion=paused?'paused':'playing';const n=document.querySelector('#motion-nav');n.setAttribute('aria-pressed',String(paused));n.setAttribute('aria-label',paused?'Play all motion':'Pause all motion');n.innerHTML=paused?'<svg viewBox="0 0 20 20" aria-hidden="true"><path d="m6 4 9 6-9 6Z"/></svg>':'<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M7 4v12M13 4v12"/></svg>'}
function animate(el,frames,options){if(paused||reduced.matches)return;const a=el.animate(frames,options);running.add(a);a.onfinish=()=>running.delete(a);return a}
function reveal(section){if(seen.has(section)||paused)return;seen.add(section);if(section.id==='opening'){section.querySelectorAll('.line>*').forEach((e,i)=>animate(e,[{transform:'translateY(105%)'},{transform:'translateY(0)'}],{duration:1050,delay:i*120,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'}));animate(section.querySelector('.hero-art'),[{transform:'scale(1.035)'},{transform:'scale(1)'}],{duration:2200,easing:'cubic-bezier(.16,1,.3,1)'});}else if(section.id==='identity'){section.querySelectorAll('.swatch').forEach((e,i)=>animate(e,[{clipPath:'inset(0 0 100% 0)'},{clipPath:'inset(0)'}],{duration:1000,delay:i*90,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'}));}else if(section.id==='logo'){animate(section.querySelector('.main-logo'),[{clipPath:'inset(0 100% 0 0)',transform:'translateY(15px)'},{clipPath:'inset(0)',transform:'translateY(0)'}],{duration:1300,easing:'cubic-bezier(.16,1,.3,1)'});}else{const heading=section.querySelector('h2');if(heading)animate(heading,[{opacity:.25,transform:'translateY(24px)',clipPath:'inset(0 0 15% 0)'},{opacity:1,transform:'translateY(0)',clipPath:'inset(0)'}],{duration:800,easing:'cubic-bezier(.16,1,.3,1)'});}}
function send(f,progress,isActive){if(!f.src||!f.contentWindow)return;f.contentWindow.postMessage({type:'portfolio-playback',progress,active:isActive},location.origin);f.dataset.progress=progress.toFixed(4)}
function measureMac(){if(!mac)return;imac.style.transform='none';macScreen.style.height='';stage.classList.remove('camera-playing');const a=imac.getBoundingClientRect(),s=stage.getBoundingClientRect(),c=macScreen.querySelector('.screen-content').getBoundingClientRect();macGeometry={left:a.left-s.left,top:a.top-s.top,ox:c.left-a.left,oy:c.top-a.top,screenHeight:macScreen.offsetHeight,scale:stage.clientWidth/c.width,border:macScreen.offsetHeight-macScreen.clientHeight};window.sizeFrames();}
function camera(time){if(!mac)return;if(!macGeometry)measureMac();const g=macGeometry;const p=reduced.matches?0:ease(clamp((time-2600)/3300));const sc=1+(g.scale-1)*p;const tx=(-g.left-g.ox*g.scale)*p,ty=(-g.top-g.oy*g.scale)*p;const targetHeight=stage.clientHeight/g.scale+g.border;macScreen.style.height=(g.screenHeight+(targetHeight-g.screenHeight)*p)+'px';imac.style.transform=`translate(${tx}px,${ty}px) scale(${sc})`;stage.classList.toggle('camera-playing',p>.1);stage.querySelector('.device-heading').style.opacity=String(1-clamp(p*1.6));stage.querySelector('.desk-plane').style.opacity=String(1-p);const wf=+macFrame.dataset.width;const mw=macFrame.parentElement.clientWidth;macFrame.style.height=(macFrame.parentElement.clientHeight/(mw/wf))+'px';const scroll=clamp((time-7000)/36000);send(macFrame,scroll,!paused);document.querySelector('#mac-state').textContent=p===0?'MAC ON TABLE / SCROLL TO ENTER':p<1?'APPROACHING THE SCREEN':'INSIDE THE LANDING PAGE';mac.dataset.cameraProgress=p.toFixed(3);mac.dataset.playbackProgress=scroll.toFixed(3);}
function updateNav(){const sections=[['story','The thinking'],['identity','The identity'],['digital','The experience'],['mobile','On mobile']];let selected='story';sections.forEach(([id])=>{if(document.querySelector('#'+id)?.getBoundingClientRect().top<innerHeight*.5)selected=id});document.querySelectorAll('.chapter-nav>a').forEach(a=>a.classList.toggle('active',a.hash==='#'+selected));document.querySelector('.progress').style.width=(scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)*100)+'%'}
function chooseActive(){let next=null,score=0;for(const [s,v] of visible){if(s.querySelector('iframe[data-page]')&&v>score){next=s;score=v}}if(active!==next){if(active)active.querySelectorAll('iframe[data-page]').forEach(f=>send(f,+(f.dataset.progress||0),false));active=next;if(active){times.set(active.id,0);active.querySelectorAll('iframe[data-page]').forEach(f=>send(f,0,!paused));}}start();}
const observer=new IntersectionObserver(es=>{for(const e of es){const s=e.target;s.classList.toggle('in-view',e.isIntersecting);visible.set(s,e.isIntersecting?e.intersectionRatio:0);if(e.isIntersecting)reveal(s);else if(s.id==='spatial'&&splineFrame)unloadScene('Scene paused while offscreen. Enter to explore again.');}chooseActive();},{threshold:[0,.1,.25,.5,.75,1]});
document.querySelectorAll('main>section').forEach(s=>observer.observe(s));
document.querySelectorAll('.screen-content').forEach(s=>{const cue=document.createElement('i');cue.className='tap-indicator';cue.setAttribute('aria-hidden','true');s.append(cue)});
function tick(now){raf=0;const dt=last?Math.max(0,now-last):0;last=now;if(paused||document.hidden||!active)return;if([...active.querySelectorAll('iframe[data-page]')].some(f=>f.dataset.ready!=='true')){last=0;raf=requestAnimationFrame(tick);return;}const id=active.id;const t=(times.get(id)||0)+dt;times.set(id,t);if(id==='digital'){camera(Math.min(t,44000));}else{const duration=id==='mobile'?36000:40000;const cycle=t%(duration+6000);const frames=[...active.querySelectorAll('iframe[data-page]')];frames.forEach((f,i)=>{const offset=id==='mobile'?i*1600:0;let p=clamp((cycle-2600-offset)/duration);if(id==='ux')p*=.6;send(f,p,true);f.parentElement.dataset.tap=String(id==='mobile'&&cycle>offset+2000&&cycle<offset+5000);});active.dataset.playbackProgress=clamp((cycle-2600)/duration).toFixed(3);}if(id==='digital'&&t>=44000){send(macFrame,1,false);return;}if(active)raf=requestAnimationFrame(tick);}
function start(){if(!raf&&!paused&&!document.hidden&&active){last=0;raf=requestAnimationFrame(tick)}}
function stop(){if(raf)cancelAnimationFrame(raf);raf=0;last=0;document.querySelectorAll('iframe[data-page]').forEach(f=>send(f,+(f.dataset.progress||0),false));}
window.restartPlayback=id=>{times.set(id,0);const s=document.querySelector('#'+id);s?.querySelectorAll('iframe[data-page]').forEach(f=>send(f,0,!paused));if(id==='digital'){measureMac();camera(0);}start()};
document.querySelectorAll('[data-replay]').forEach(b=>b.onclick=()=>{if(paused&&!reduced.matches){paused=false;reflectPause()}window.restartPlayback(b.dataset.replay)});
if(mac)document.querySelector('#replay-mac').onclick=()=>{mac.scrollIntoView({behavior:'smooth',block:'start'});if(paused&&!reduced.matches){paused=false;reflectPause()}window.restartPlayback('digital')};
toggle.onclick=()=>{paused=!paused;reflectPause();if(paused){stop();document.querySelectorAll('video').forEach(v=>v.pause());for(const a of running)a.pause();if(splineFrame)unloadScene('Motion paused. Enter the scene when ready.');}else{for(const a of running)a.play();for(const [s,v] of visible)if(v)reveal(s);start()}};
document.querySelector('#motion-nav').onclick=()=>toggle.onclick();
reduced.addEventListener('change',()=>{paused=reduced.matches;reflectPause();if(paused){stop();for(const a of running)a.finish();measureMac();camera(0);if(splineFrame)unloadScene('Reduced motion enabled. Enter the scene to explore.');}else start()});
document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();for(const a of running)a.pause();if(splineFrame)unloadScene('Scene paused while the page was hidden.');}else{if(!paused)for(const a of running)a.play();start()}});
let resizeTimer;window.addEventListener('resize',()=>{clearTimeout(resizeTimer);resizeTimer=setTimeout(()=>{measureMac();if(active===mac)camera(times.get('digital')||0);updateNav()},120)});
let navRaf;window.addEventListener('scroll',()=>{if(!navRaf)navRaf=requestAnimationFrame(()=>{navRaf=0;updateNav()})},{passive:true});
const spatial=document.querySelector('#spatial'),status=document.querySelector('#scene-status'),loadButton=document.querySelector('#load-scene'),unloadButton=document.querySelector('#unload-scene');
function unloadScene(message){clearTimeout(sceneTimeout);splineFrame?.remove();splineFrame=null;spatial.classList.remove('spline-active');spatial.dataset.scene='idle';loadButton.disabled=false;loadButton.innerHTML='Explore the original '+arrow;unloadButton.hidden=true;status.textContent=message||'Original project scene';}
if(loadButton)loadButton.onclick=()=>{if(splineFrame)return;status.textContent='Loading the original scene…';loadButton.disabled=true;loadButton.textContent='Loading scene…';splineFrame=document.createElement('iframe');splineFrame.title='Original '+P.name+' interactive scene';splineFrame.src=P.scene.kind==='web'?P.scene.url:'scene.html?project='+P.id;if(P.scene.kind==='web')splineFrame.onload=()=>{clearTimeout(sceneTimeout);spatial.classList.add('spline-active');spatial.dataset.scene='ready';status.textContent='Explore the original experience';};splineFrame.setAttribute('sandbox','allow-scripts allow-same-origin');document.querySelector('#spline-slot').prepend(splineFrame);if(P.scene.kind==='web')spatial.classList.add('spline-active');spatial.dataset.scene='loading';unloadButton.hidden=false;sceneTimeout=setTimeout(()=>{if(spatial.dataset.scene==='loading')status.textContent='The original scene is taking longer to load. You can return to the still.'},20000)};
if(unloadButton)unloadButton.onclick=()=>{unloadScene();loadButton.focus()};
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.source!==splineFrame?.contentWindow)return;if(e.data?.type==='scene-ready'){clearTimeout(sceneTimeout);spatial.classList.add('spline-active');spatial.dataset.scene='ready';status.textContent='Move your pointer to explore';}if(e.data?.type==='scene-error'){unloadScene('The scene could not load. Try again to reconnect.')}});
reflectPause();measureMac();updateNav();reveal(document.querySelector('#opening'));
})();
