window.addEventListener('error',e=>{if(e.message)document.body.dataset.previewError=e.message});
window.addEventListener('unhandledrejection',e=>{document.body.dataset.previewError=String(e.reason?.message||e.reason)});
const A='../recent-case-studies/assets/';
const arrow='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12h15m-6-6 6 6-6 6"/></svg>';
const image=(file,alt,cls='',eager=false)=>`<img class="${cls}" src="${A+file}" alt="${alt}" ${eager?'fetchpriority="high"':'loading="lazy"'}>`;
const brandImage=(file,alt,cls='')=>`<img class="${cls}" src="brand/${file}.svg" alt="${alt}">`;
const tag=(n,text)=>`<div class="eyebrow"><span>${n}</span>${text}</div>`;
const sectionTitle=(n,label,title)=>`${tag(n,label)}<h2 class="reveal">${title}</h2>`;
const frame=(page,label,kind='desktop')=>`<div class="screen-content screen-${kind}"><iframe inert aria-hidden="true" data-page="${page}" data-width="${kind==='mobile'?390:1440}" title="${label} — guided page playback" tabindex="-1" sandbox="allow-scripts allow-same-origin" loading="lazy"></iframe></div>`;
const phone=(page,label,cls)=>`<div class="phone ${cls}"><div class="phone-screen">${frame(page,label,'mobile')}</div><i class="island" aria-hidden="true"></i><i class="home-indicator" aria-hidden="true"></i><span class="phone-label">${label}</span></div>`;
const laptop=(page,label,cls)=>`<div class="laptop ${cls}"><div class="laptop-lid"><i class="lens" aria-hidden="true"></i><div class="laptop-screen">${frame(page,label)}</div><div class="laptop-chin">MacBook Pro</div></div><div class="laptop-base"><i></i></div><span class="laptop-caption">${label}</span></div>`;
const caseData={name:'NeoLabCare',scopeRefs:['strategy','identity','packaging','digital'],scopes:{strategy:{name:'Brand strategy',description:'The proposition, its priorities and the principles used to make design decisions.',links:[['Project goal & our solution','#story'],['Style strategy','#strategy']]},identity:{name:'Visual identity',description:'A connected language of color, typography, marks and product imagery.',links:[['Color palette','#identity'],['Typography','#typography'],['Brand logo & variations','#logo']]},packaging:{name:'Packaging & art direction',description:'The identity expressed through the original bottle, packaging and brand-world imagery.',links:[['Style strategy','#strategy'],['Identity in the physical world','#applications'],['Spatial product scene','#spatial']]},digital:{name:'UX/UI & website',description:'A path from understanding the proposition to exploring the story, freshness and reservation.',links:[['UX/UI decisions','#ux'],['Landing page','#digital'],['Other key pages','#paired'],['Page gallery','#gallery'],['Mobile experience','#mobile']]}}};
window.caseData=caseData;
document.querySelector('#case').innerHTML=`
<section class="hero dark" id="opening" aria-labelledby="hero-title">
 <div class="hero-art">${image('neolabcare/portal.webp','NeoLabCare bottle suspended in its original illuminated portal landscape','',true)}</div>
 <div class="hero-copy"><p class="project-type">Brand strategy / Identity / Digital experience</p>${brandImage('gold','NeoLabCare','hero-logo')}<h1 id="hero-title"><span class="line"><span>A daily ritual,</span></span><span class="line"><em>reconsidered.</em></span></h1><p class="hero-deck">Strategy, identity and digital experience for a simpler daily ritual.</p><a class="text-link" href="#story">Explore the collaboration ${arrow}</a></div>
 <div class="hero-bottom"><span>A PULSE CASE STUDY</span><span>NEOLABCARE — BRAND & PRODUCT EXPERIENCE</span><a href="#story" aria-label="Scroll to the story">↓</a></div>
</section>
<section class="story paper chapter" id="story">
 <div class="project-details"><div><span class="meta-label">Project</span><p>NeoLabCare</p></div><div><span class="meta-label">Project type</span><p>Founder-led brand & product experience</p></div><div class="scope-meta"><span class="meta-label">Project scope</span><div class="scope-list">${caseData.scopeRefs.map(id=>`<button data-scope="${id}">${caseData.scopes[id].name}<span>↗</span></button>`).join('')}</div></div></div>
 <div class="story-main">${sectionTitle('01','THE COLLABORATION','Less to navigate.<br><em>More to believe in.</em>')}<div class="story-columns"><article><h3>Project goal</h3><p>Make a simpler personal-care ritual clear, credible and easy to navigate.</p></article><article><h3>Our solution</h3><p>Connect strategy, identity, packaging and website through one idea: considered simplicity.</p></article></div></div>
 
</section>
<section class="strategy dark chapter" id="strategy"><div class="strategy-art">${image('neolabcare/hand.webp','NeoLabCare bottle held in a hand')}</div><div class="strategy-copy">${sectionTitle('02','STYLE STRATEGY','Less noise.<br><em>More intention.</em>')}<div class="principles"><article><span>01</span><div><h3>Precision</h3><p>Clear type. Controlled geometry.</p></div></article><article><span>02</span><div><h3>Restraint</h3><p>A limited palette. Room to breathe.</p></div></article><article><span>03</span><div><h3>Humanity</h3><p>Warm gold. Tactile imagery.</p></div></article></div></div></section>
<section class="palette paper chapter" id="identity"><div class="split-heading">${sectionTitle('03','COLOR PALETTE','A quiet kind<br>of <em>contrast.</em>')}</div><div class="swatches">${[['Obsidian','#0A0A0A','Foundation'],['Sand gold','#C8B89A','Signature'],['Gold light','#E0D0B0','Light accent'],['Off white','#F5F5F0','Breathing space']].map(([name,hex,role],i)=>`<button class="swatch swatch-${i}" style="--color:${hex}" data-color="${hex}" aria-label="Inspect ${name} ${hex}"><span class="swatch-index">0${i+1}</span><div><h3>${name}</h3><p>${role}</p><span>${hex}</span></div><i aria-hidden="true">+</i></button>`).join('')}</div><p class="palette-status" id="palette-status" aria-live="polite">Select a color.</p></section>
<section class="typography paper chapter" id="typography"><div class="type-top">${tag('04','TYPOGRAPHY')}<span>Poppins / Geometric sans serif</span></div><div class="type-main"><div class="type-aa">Aa</div><div><h2>Clarity has<br>a character.</h2></div></div><div class="type-controls"><label for="weight">Weight<select id="weight"><option value="300">Light / 300</option><option value="400" selected>Regular / 400</option><option value="500">Medium / 500</option><option value="600">Semibold / 600</option></select></label><label for="specimen-input">Try your own words<input id="specimen-input" maxlength="80" value="Considered, in every detail."></label></div><p id="type-specimen">Considered, in every detail.</p><div class="alphabet">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz &nbsp; 0123456789</div></section>
<section class="logo dark chapter" id="logo"><div class="logo-top">${tag('05','THE BRAND MARK')}</div><div class="logo-orbit" aria-hidden="true"></div>${brandImage('gold','NeoLabCare original live-site wordmark','main-logo')}<div class="logo-bottom"><span>NEOLABCARE</span></div></section>
<section class="variations chapter" id="variations" aria-label="Logo variations">${[['gold','dark','Sand gold on obsidian'],['dark','gold-ground','Dark on sand'],['grey','slate','Grey on gold light'],['icon','pale','Standalone symbol']].map(([file,cls,label],i)=>`<div class="mark-cell ${cls}">${brandImage(file,label)}<div><span>${i===0?'06 / LOGO VARIATIONS':'0'+(i+1)}</span><span>${label}</span></div></div>`).join('')}</section>
<section class="applications dark chapter" id="applications"><div class="application-heading">${sectionTitle('07','THE IDENTITY IN USE','From an identity<br>to <em>an object.</em>')}</div><div class="application-images"><figure>${image('neolabcare/packaging-world.webp','NeoLabCare original packaging and bottle study')}<figcaption>Packaging</figcaption></figure><figure>${image('neolabcare/exploded.webp','NeoLabCare original exploded bottle visualization')}<figcaption>Product architecture</figcaption></figure></div></section>
<section class="ux paper chapter" id="ux"><div class="ux-copy">${sectionTitle('08','UX / UI','An invitation.<br>A reason.<br><em>A next step.</em>')}<div class="flow-steps"><button data-flow="index" aria-pressed="true"><span>01</span><div>Arrive</div>${arrow}</button><button data-flow="freshness" aria-pressed="false"><span>02</span><div>Understand</div>${arrow}</button><button data-flow="crowdfunding" aria-pressed="false"><span>03</span><div>Take part</div>${arrow}</button></div></div><div class="ux-device">${phone('index','The welcome page','ux-phone')}<span class="device-note" id="flow-note">01 / Arrive at the idea</span></div></section>
<section class="desktop-chapter chapter" id="digital"><div class="desktop-stage"><div class="device-heading">${sectionTitle('09','THE LANDING EXPERIENCE','Step into<br><em>the experience.</em>')}</div><div class="desk-wall" aria-hidden="true"></div><div class="desk-plane" aria-hidden="true"></div><div class="imac"><div class="imac-frame"><div class="imac-screen">${frame('index','NeoLabCare landing page')}</div><div class="imac-chin"><i></i></div></div><div class="imac-neck"></div><div class="imac-foot"></div></div><div class="scene-controls"><span id="mac-state">MAC ON TABLE / SCROLL TO ENTER</span><button id="replay-mac">Replay approach ${arrow}</button></div></div></section>
<div class="screen-footnote"><span>The original website</span><a href="https://www.neolabcare.com/" target="_blank" rel="noopener">Explore the website ↗</a></div>
<section class="spatial dark chapter" id="spatial"><div class="spatial-heading">${sectionTitle('10','3D / THE BRAND WORLD','A world with<br><em>dimension.</em>')}</div><div id="spline-slot" class="spline-slot">${image('neolabcare/portal.webp','NeoLabCare portal — preview of the original interactive scene','spline-poster')}<div class="scene-launch"><button id="load-scene" class="solid-button">Enter the 3D scene ${arrow}</button><span id="scene-status" role="status">Original interactive Spline scene</span></div></div><div class="spatial-bottom"><span>ORIGINAL PROJECT SCENE</span><button id="unload-scene" hidden>Return to the still ${arrow}</button></div></section>
<section class="paired paper chapter" id="paired"><div class="paired-heading">${sectionTitle('11','OTHER KEY PAGES','Two perspectives.<br><em>One language.</em>')}</div><div class="paired-laptops" data-focus="both">${laptop('story','01 / The story','upper')}${laptop('freshness','02 / Freshness','lower')}</div><div class="pair-controls" aria-label="Inspect laptop screens"><button data-focus="upper" aria-pressed="false">The story</button><button data-focus="both" aria-pressed="true">Both screens</button><button data-focus="lower" aria-pressed="false">Freshness</button><button data-replay="paired" aria-label="Replay both page scrolls">Replay ↻</button></div></section>
<section class="gallery paper chapter" id="gallery"><div class="gallery-heading">${sectionTitle('12','PAGE ANIMATION GALLERY','Every page,<br><em>a purpose.</em>')}<div class="gallery-tabs" aria-label="Select a page"><button data-gallery="crowdfunding" aria-pressed="true"><span>01</span> The reservation</button><button data-gallery="creator-partner" aria-pressed="false"><span>02</span> The creator invitation</button><button data-gallery="story" aria-pressed="false"><span>03</span> The founder’s story</button></div></div><div class="browser-frame"><div class="browser-bar"><div><i></i><i></i><i></i></div><span id="gallery-address">neolabcare.com / reservation</span><button data-replay="gallery" aria-label="Replay selected page">↻</button></div><div class="gallery-screen">${frame('crowdfunding','NeoLabCare reservation')}</div></div></section>
<section class="mobile chapter" id="mobile"><div class="mobile-heading">${sectionTitle('13','THE MOBILE EXPERIENCE','A smaller screen.<br><em>The same intention.</em>')}</div><div class="phone-group">${phone('index','01 / Welcome','phone-left')}${phone('freshness','02 / Understand','phone-center')}${phone('crowdfunding','03 / Take part','phone-right')}</div><div class="mobile-controls"><span>THREE MOMENTS / ONE JOURNEY</span><button data-replay="mobile">Replay the journey ${arrow}</button></div></section>
<section class="reflection paper chapter" id="reflection"><div>${tag('14','LOOKING AT THE WHOLE')}<h2>A coherent world.<br><em>From idea to interaction.</em></h2></div><div class="reflection-copy"><details class="credits"><summary>Case notes & project credits <span>+</span></summary><p>Original project work. Individual and specialist credits await confirmation.</p><p>Website captures and scrolling exhibits; original interactive Spline scene.</p><a href="SOURCES.md" target="_blank">View the source register ↗</a></details></div></section>
<footer class="case-footer dark"><p>NEOLABCARE / A PULSE CASE STUDY</p><a href="../recent-case-studies/">Back to<br><em>the collection.</em>${arrow}</a><div><span>Strategy. Identity. Experience.</span><a href="#opening">Back to top ↑</a></div></footer>`;
const chapters=[['opening','Opening'],['story','Goal & solution'],['strategy','Style strategy'],['identity','Color palette'],['typography','Typography'],['logo','Brand logo'],['variations','Logo variations'],['applications','Identity in use'],['ux','UX / UI'],['digital','Mac landing experience'],['spatial','Original 3D scene'],['paired','Paired MacBooks'],['gallery','Page gallery'],['mobile','Mobile experience'],['reflection','Reflection & credits']];
document.querySelector('#index-links').innerHTML=chapters.map(([id,label],i)=>`<a href="#${id}"><span>${String(i+1).padStart(2,'0')}</span>${label}${arrow}</a>`).join('');
const indexDialog=document.querySelector('#index-dialog'),scopeDialog=document.querySelector('#scope-dialog');
document.querySelector('#index-open').onclick=()=>indexDialog.showModal();document.querySelector('#index-close').onclick=()=>indexDialog.close();document.querySelector('#scope-close').onclick=()=>scopeDialog.close();
document.querySelectorAll('#index-links a').forEach(a=>a.onclick=()=>indexDialog.close());
for(const d of [indexDialog,scopeDialog])d.addEventListener('click',e=>{if(e.target===d){const b=d.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)d.close()}});
document.querySelectorAll('[data-scope]').forEach(b=>b.onclick=()=>{const s=caseData.scopes[b.dataset.scope];document.querySelector('#scope-name').textContent=s.name;document.querySelector('#scope-description').textContent=s.description;document.querySelector('#scope-links').innerHTML=s.links.map(([label,url])=>`<a href="${url}">${label} ${arrow}</a>`).join('');document.querySelectorAll('#scope-links a').forEach(a=>a.onclick=()=>scopeDialog.close());scopeDialog.showModal()});
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-color]').forEach(x=>x.removeAttribute('aria-pressed'));b.setAttribute('aria-pressed','true');document.querySelector('#palette-status').textContent=b.querySelector('h3').textContent+' / '+b.dataset.color+' / '+b.querySelector('p').textContent});
document.querySelector('#weight').onchange=e=>document.querySelector('#type-specimen').style.fontWeight=e.target.value;
document.querySelector('#specimen-input').oninput=e=>document.querySelector('#type-specimen').textContent=e.target.value||'Considered, in every detail.';
function sizeFrame(f){const wrap=f.parentElement;const w=+f.dataset.width;f.style.width=w+'px';f.style.height=(wrap.clientHeight/(wrap.clientWidth/w))+'px';f.style.transform=`scale(${wrap.clientWidth/w})`;}
window.sizeFrames=()=>document.querySelectorAll('iframe[data-page]').forEach(sizeFrame);
const frameObserver=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const f=e.target;if(!f.src){f.src='pages/'+f.dataset.page+'.html';f.onload=()=>sizeFrame(f)}sizeFrame(f);}}),{rootMargin:'500px'});
document.querySelectorAll('iframe[data-page]').forEach(f=>frameObserver.observe(f));
new ResizeObserver(()=>window.sizeFrames()).observe(document.querySelector('#case'));
function changeFrame(f,page){f.dataset.page=page;delete f.dataset.ready;f.src='pages/'+page+'.html';f.onload=()=>sizeFrame(f);f.closest('section').dataset.playbackStart='';window.restartPlayback?.(f.closest('section').id)}
document.querySelectorAll('[data-flow]').forEach((b,i)=>b.onclick=()=>{document.querySelectorAll('[data-flow]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));changeFrame(document.querySelector('.ux iframe'),b.dataset.flow);document.querySelector('#flow-note').textContent=['01 / Arrive at the idea','02 / Understand the rationale','03 / A clear next step'][i]});
document.querySelectorAll('button[data-focus]').forEach(b=>b.onclick=()=>{document.querySelector('.paired-laptops').dataset.focus=b.dataset.focus;document.querySelectorAll('button[data-focus]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));setTimeout(window.sizeFrames,50)});
document.querySelectorAll('[data-gallery]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-gallery]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));changeFrame(document.querySelector('.gallery iframe'),b.dataset.gallery);document.querySelector('#gallery-address').textContent='neolabcare.com / '+(b.dataset.gallery==='crowdfunding'?'reservation':b.dataset.gallery)});
window.addEventListener('message',e=>{if(e.origin!==location.origin||e.data?.type!=='portfolio-ready')return;document.querySelectorAll('iframe[data-page]').forEach(f=>{if(f.contentWindow===e.source){f.dataset.ready='true';sizeFrame(f)}})});
window.sizeFrames();
